apiVersion: v1
kind: Secret
metadata:
  name: ai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1ncDNiTXRzTWhjNkp0eXEzc0V5SXlRTnRNOXQzRlZsMFA2VURwcWlVdVNNcnY2U0VYWDFVMmdGUlhGNkRyTHdNZ0VFbDd6Y1ZHQVQzQmxia0ZKbWlmaTczUjV1WWZ1b3FRNnFHeThkNHlrUTBQLVBpX2hYNjdzQmk0VnZlWENJRVJESndFcmNXcHJ1N19jN0w1TlBnd1UxdFFjSUE==